var Constants = {
		
	ORDER_NEW : 1,
	ORDER_WELCOMER_NEW : 2,
	ORDER_WAITING : 3,
	ORDER_COMMITED : 4,
	ORDER_PAYING : 5,
	ORDER_FINISHED : 6,
	ORDER_UNAVAILABLE : 7,
	ORDER_AVAILABLE : 8,
		
	//food status
	FOOD_NEW : 1,
	FOOD_CONFIRMED : 2,
	FOOD_COOKING : 3,
	FOOD_FINISHED : 4,
	FOOD_UNAVAILABLE : 5,
	FOOD_AVAILABLE : 6,
	
	FOOD_STATUS_OK : 1,
	FOOD_STATUS_NO : 0,
	
	SUCCESS : 1,
	FAIL : 2,
	
};